// RiveElasticCurve-standalone.jsx
// 单文件版本：所有依赖已合并，无需外部文件
// 版本: 1.0.4 - 修复 UI 显示问题（dialog 窗口）

/**
 * Rive 弹性曲线插件 - 单文件版本
 * 版本: 1.0.4
 * 作者: Personal
 * 描述: 将 Rive 弹性曲线应用到 After Effects 关键帧
 * 
 * 使用说明：
 * 1. 在 After Effects 中打开此脚本
 * 2. 选择需要应用弹性曲线的属性（位置、缩放、旋转等）
 * 3. 确保属性至少有 2 个关键帧
 * 4. 调整参数后点击"应用到选中关键帧"
 */

// ============================================================
// PART 1: ElasticCurveModel - 数据模型
// ============================================================

/**
 * Rive 弹性曲线模型
 * @constructor
 */
function ElasticCurveModel() {
    // 私有属性
    var _amplitude = 1.0;
    var _period = 0.5;
    var _easingType = 'easeOut';
    
    // 参数范围
    var AMPLITUDE_MIN = 0.1;
    var AMPLITUDE_MAX = 10.0;
    var PERIOD_MIN = 0.1;
    var PERIOD_MAX = 5.0;
    var EASING_TYPES = ['easeIn', 'easeOut', 'easeInOut'];
    
    /**
     * 获取振幅
     * @returns {number}
     */
    this.getAmplitude = function() {
        return _amplitude;
    };
    
    /**
     * 设置振幅
     * @param {number} value
     * @returns {boolean} 是否设置成功
     */
    this.setAmplitude = function(value) {
        var num = parseFloat(value);
        if (isNaN(num) || num < AMPLITUDE_MIN || num > AMPLITUDE_MAX) {
            return false;
        }
        _amplitude = num;
        return true;
    };
    
    /**
     * 获取周期
     * @returns {number}
     */
    this.getPeriod = function() {
        return _period;
    };
    
    /**
     * 设置周期
     * @param {number} value
     * @returns {boolean} 是否设置成功
     */
    this.setPeriod = function(value) {
        var num = parseFloat(value);
        if (isNaN(num) || num < PERIOD_MIN || num > PERIOD_MAX) {
            return false;
        }
        _period = num;
        return true;
    };
    
    /**
     * 获取缓动类型
     * @returns {string}
     */
    this.getEasingType = function() {
        return _easingType;
    };
    
    /**
     * 设置缓动类型
     * @param {string} type
     * @returns {boolean} 是否设置成功
     */
    this.setEasingType = function(type) {
        if (EASING_TYPES.indexOf(type) === -1) {
            return false;
        }
        _easingType = type;
        return true;
    };
    
    /**
     * 获取所有参数
     * @returns {Object}
     */
    this.getAll = function() {
        return {
            amplitude: _amplitude,
            period: _period,
            easingType: _easingType
        };
    };
    
    /**
     * 重置为默认值
     */
    this.reset = function() {
        _amplitude = 1.0;
        _period = 0.5;
        _easingType = 'easeOut';
    };
    
    /**
     * 验证所有参数
     * @returns {Object} {valid: boolean, errors: Array}
     */
    this.validate = function() {
        var errors = [];
        
        if (_amplitude < AMPLITUDE_MIN || _amplitude > AMPLITUDE_MAX) {
            errors.push('振幅必须在 ' + AMPLITUDE_MIN + ' 到 ' + AMPLITUDE_MAX + ' 之间');
        }
        
        if (_period < PERIOD_MIN || _period > PERIOD_MAX) {
            errors.push('周期必须在 ' + PERIOD_MIN + ' 到 ' + PERIOD_MAX + ' 之间');
        }
        
        if (EASING_TYPES.indexOf(_easingType) === -1) {
            errors.push('无效的缓动类型');
        }
        
        return {
            valid: errors.length === 0,
            errors: errors
        };
    };
    
    /**
     * 获取参数范围
     * @returns {Object}
     */
    this.getRanges = function() {
        return {
            amplitude: { min: AMPLITUDE_MIN, max: AMPLITUDE_MAX },
            period: { min: PERIOD_MIN, max: PERIOD_MAX },
            easingTypes: EASING_TYPES
        };
    };
}


// ============================================================
// PART 2: ExpressionGenerator - 表达式生成器
// ============================================================

/**
 * Rive 弹性曲线表达式生成器
 * @constructor
 */
function ExpressionGenerator() {
    
    /**
     * 生成 AE 表达式代码
     * @param {number} amplitude - 振幅
     * @param {number} period - 周期
     * @param {string} easingType - 缓动类型 ('easeIn' | 'easeOut' | 'easeInOut')
     * @returns {string} AE 表达式代码
     */
    this.generate = function(amplitude, period, easingType) {
        var expression = '';
        
        // 表达式头部：参数定义
        expression += '// Rive Elastic Curve\n';
        expression += '// Generated by Rive Elastic Curve Plugin\n';
        expression += '\n';
        expression += '// 参数\n';
        expression += 'var amplitude = ' + amplitude + ';\n';
        expression += 'var period = ' + period + ';\n';
        expression += 'var PI = Math.PI;\n';
        expression += '\n';
        
        // 计算相位偏移 s
        expression += '// 计算相位偏移\n';
        expression += 'var s = amplitude < 1.0 \n';
        expression += '    ? period / 4.0 \n';
        expression += '    : period / (2.0 * PI) * Math.asin(1.0 / amplitude);\n';
        expression += '\n';
        
        // 实际振幅计算函数
        expression += '// 计算实际振幅\n';
        expression += 'function computeActualAmplitude(time) {\n';
        expression += '    if (amplitude < 1.0) {\n';
        expression += '        var t = Math.abs(s);\n';
        expression += '        var absTime = Math.abs(time);\n';
        expression += '        if (absTime < t) {\n';
        expression += '            var l = absTime / t;\n';
        expression += '            return (amplitude * l) + (1.0 - l);\n';
        expression += '        }\n';
        expression += '    }\n';
        expression += '    return amplitude;\n';
        expression += '}\n';
        expression += '\n';
        
        // 根据缓动类型生成对应的函数
        switch (easingType) {
            case 'easeOut':
                expression += this._generateEaseOut();
                break;
            case 'easeIn':
                expression += this._generateEaseIn();
                break;
            case 'easeInOut':
                expression += this._generateEaseInOut();
                break;
            default:
                expression += this._generateEaseOut(); // 默认 easeOut
        }
        
        expression += '\n';
        
        // 应用到关键帧
        expression += '// 应用到关键帧\n';
        expression += 'if (numKeys > 0) {\n';
        expression += '    var key1 = nearestKey(time);\n';
        expression += '    var keyIndex = key1.index;\n';
        expression += '    \n';
        expression += '    if (time < key1.time) {\n';
        expression += '        keyIndex--;\n';
        expression += '    }\n';
        expression += '    \n';
        expression += '    if (keyIndex > 0 && keyIndex < numKeys) {\n';
        expression += '        var t1 = key(keyIndex).time;\n';
        expression += '        var t2 = key(keyIndex + 1).time;\n';
        expression += '        var v1 = key(keyIndex);\n';
        expression += '        var v2 = key(keyIndex + 1);\n';
        expression += '        \n';
        expression += '        if (time >= t1 && time <= t2) {\n';
        expression += '            var duration = t2 - t1;\n';
        expression += '            var progress = (time - t1) / duration;\n';
        expression += '            var factor = elasticEase(progress);\n';
        expression += '            \n';
        expression += '            value = v1 + (v2 - v1) * factor;\n';
        expression += '        } else {\n';
        expression += '            value;\n';
        expression += '        }\n';
        expression += '    } else {\n';
        expression += '        value;\n';
        expression += '    }\n';
        expression += '} else {\n';
        expression += '    value;\n';
        expression += '}';
        
        return expression;
    };
    
    /**
     * 生成 Ease Out 函数
     * @private
     */
    this._generateEaseOut = function() {
        var code = '';
        code += '// Ease Out 函数\n';
        code += 'function elasticEase(factor) {\n';
        code += '    var time = factor;\n';
        code += '    var actualAmplitude = computeActualAmplitude(time);\n';
        code += '    \n';
        code += '    return actualAmplitude * Math.pow(2.0, -10.0 * time) * \n';
        code += '           Math.sin((time - s) * (2.0 * PI) / period) + 1.0;\n';
        code += '}\n';
        return code;
    };
    
    /**
     * 生成 Ease In 函数
     * @private
     */
    this._generateEaseIn = function() {
        var code = '';
        code += '// Ease In 函数\n';
        code += 'function elasticEase(factor) {\n';
        code += '    var time = factor - 1.0;\n';
        code += '    var actualAmplitude = computeActualAmplitude(time);\n';
        code += '    \n';
        code += '    return -(actualAmplitude * Math.pow(2.0, 10.0 * time) * \n';
        code += '             Math.sin((-time - s) * (2.0 * PI) / period));\n';
        code += '}\n';
        return code;
    };
    
    /**
     * 生成 Ease In-Out 函数
     * @private
     */
    this._generateEaseInOut = function() {
        var code = '';
        code += '// Ease In-Out 函数\n';
        code += 'function elasticEase(factor) {\n';
        code += '    var time = factor * 2.0 - 1.0;\n';
        code += '    var actualAmplitude = computeActualAmplitude(time);\n';
        code += '    \n';
        code += '    if (time < 0.0) {\n';
        code += '        return -0.5 * actualAmplitude * Math.pow(2.0, 10.0 * time) * \n';
        code += '               Math.sin((-time - s) * (2.0 * PI) / period);\n';
        code += '    } else {\n';
        code += '        return 0.5 * (actualAmplitude * Math.pow(2.0, -10.0 * time) * \n';
        code += '               Math.sin((time - s) * (2.0 * PI) / period)) + 1.0;\n';
        code += '    }\n';
        code += '}\n';
        return code;
    };
    
    /**
     * 生成简化版表达式（用于预览）
     * @param {number} amplitude
     * @param {number} period
     * @param {string} easingType
     * @returns {string}
     */
    this.generateSimplified = function(amplitude, period, easingType) {
        return 'Rive Elastic (' + easingType + ')\n' +
               'Amplitude: ' + amplitude + '\n' +
               'Period: ' + period;
    };
}


// ============================================================
// PART 3: ElasticCurveViewModel - 业务逻辑层
// ============================================================

/**
 * Rive 弹性曲线 ViewModel
 * @constructor
 * @param {ElasticCurveModel} model - 数据模型
 * @param {ExpressionGenerator} generator - 表达式生成器
 */
function ElasticCurveViewModel(model, generator) {
    var _model = model;
    var _generator = generator;
    var _view = null;
    
    /**
     * 绑定 View
     * @param {Object} view
     */
    this.bindView = function(view) {
        _view = view;
    };
    
    /**
     * 更新振幅
     * @param {string} value
     * @returns {Object} {success: boolean, error: string}
     */
    this.updateAmplitude = function(value) {
        if (_model.setAmplitude(value)) {
            return { success: true };
        } else {
            var ranges = _model.getRanges();
            return { 
                success: false, 
                error: '振幅必须在 ' + ranges.amplitude.min + ' 到 ' + ranges.amplitude.max + ' 之间'
            };
        }
    };
    
    /**
     * 更新周期
     * @param {string} value
     * @returns {Object} {success: boolean, error: string}
     */
    this.updatePeriod = function(value) {
        if (_model.setPeriod(value)) {
            return { success: true };
        } else {
            var ranges = _model.getRanges();
            return { 
                success: false, 
                error: '周期必须在 ' + ranges.period.min + ' 到 ' + ranges.period.max + ' 之间'
            };
        }
    };
    
    /**
     * 更新缓动类型
     * @param {string} type
     * @returns {Object} {success: boolean, error: string}
     */
    this.updateEasingType = function(type) {
        if (_model.setEasingType(type)) {
            return { success: true };
        } else {
            return { 
                success: false, 
                error: '无效的缓动类型'
            };
        }
    };
    
    /**
     * 获取当前参数
     * @returns {Object}
     */
    this.getCurrentParams = function() {
        return _model.getAll();
    };
    
    /**
     * 生成表达式
     * @returns {string}
     */
    this.generateExpression = function() {
        var params = _model.getAll();
        return _generator.generate(
            params.amplitude,
            params.period,
            params.easingType
        );
    };
    
    /**
     * 应用到选中的属性
     * @returns {Object} {success: boolean, message: string, count: number}
     */
    this.applyToSelectedProperties = function() {
        try {
            // 验证参数
            var validation = _model.validate();
            if (!validation.valid) {
                return {
                    success: false,
                    message: '参数验证失败：\n' + validation.errors.join('\n'),
                    count: 0
                };
            }
            
            // 获取当前 AE 项目
            var comp = app.project.activeItem;
            if (!comp || !(comp instanceof CompItem)) {
                return {
                    success: false,
                    message: '请先打开一个合成',
                    count: 0
                };
            }
            
            // 获取选中的属性
            var selectedProperties = comp.selectedProperties;
            if (selectedProperties.length === 0) {
                return {
                    success: false,
                    message: '请先选中至少一个属性（如位置、缩放、旋转等）',
                    count: 0
                };
            }
            
            // 生成表达式
            var expression = this.generateExpression();
            
            // 应用到每个选中的属性
            var appliedCount = 0;
            var errors = [];
            
            app.beginUndoGroup('应用 Rive 弹性曲线');
            
            for (var i = 0; i < selectedProperties.length; i++) {
                var prop = selectedProperties[i];
                
                // 检查属性是否可以添加表达式
                if (prop.canSetExpression) {
                    try {
                        // 检查是否有关键帧
                        if (prop.numKeys < 2) {
                            errors.push(prop.name + ': 需要至少 2 个关键帧');
                            continue;
                        }
                        
                        // 启用表达式
                        prop.expressionEnabled = true;
                        
                        // 设置表达式
                        prop.expression = expression;
                        
                        appliedCount++;
                    } catch (e) {
                        errors.push(prop.name + ': ' + e.toString());
                    }
                } else {
                    errors.push(prop.name + ': 不支持表达式');
                }
            }
            
            app.endUndoGroup();
            
            // 返回结果
            if (appliedCount > 0) {
                var message = '成功应用到 ' + appliedCount + ' 个属性';
                if (errors.length > 0) {
                    message += '\n\n部分失败：\n' + errors.join('\n');
                }
                return {
                    success: true,
                    message: message,
                    count: appliedCount
                };
            } else {
                return {
                    success: false,
                    message: '应用失败：\n' + errors.join('\n'),
                    count: 0
                };
            }
            
        } catch (e) {
            return {
                success: false,
                message: '发生错误：' + e.toString(),
                count: 0
            };
        }
    };
    
    /**
     * 重置参数
     */
    this.reset = function() {
        _model.reset();
        if (_view && _view.updateFromModel) {
            _view.updateFromModel(_model.getAll());
        }
    };
    
    /**
     * 获取参数范围
     * @returns {Object}
     */
    this.getRanges = function() {
        return _model.getRanges();
    };
    
    /**
     * 预览表达式（简化版）
     * @returns {string}
     */
    this.previewExpression = function() {
        var params = _model.getAll();
        return _generator.generateSimplified(
            params.amplitude,
            params.period,
            params.easingType
        );
    };
}


// ============================================================
// PART 4: ElasticCurveView - UI 界面层
// ============================================================

/**
 * Rive 弹性曲线 View
 * @constructor
 * @param {ElasticCurveViewModel} viewModel - ViewModel 实例
 */
function ElasticCurveView(viewModel) {
    var _viewModel = viewModel;
    var _window = null;
    var _controls = {};
    
    /**
     * 构建 UI
     * @returns {Window}
     */
    this.build = function() {
        // 创建对话框窗口（使用 dialog 而非 palette 以支持"运行脚本文件"方式）
        _window = new Window('dialog', 'Rive Elastic Curve', undefined, {
            resizeable: false
        });
        
        _window.orientation = 'column';
        _window.alignChildren = ['fill', 'top'];
        _window.spacing = 10;
        _window.margins = 16;
        
        // 标题
        var titleGroup = _window.add('group');
        titleGroup.orientation = 'row';
        titleGroup.alignChildren = ['left', 'center'];
        var titleText = titleGroup.add('statictext', undefined, 'Rive 弹性曲线');
        titleText.graphics.font = ScriptUI.newFont('dialog', 'BOLD', 14);
        
        // 分隔线
        _window.add('panel', undefined, '', {borderStyle: 'black'});
        
        // 参数输入区域
        var paramsGroup = _window.add('group');
        paramsGroup.orientation = 'column';
        paramsGroup.alignChildren = ['fill', 'top'];
        paramsGroup.spacing = 8;
        
        // 振幅输入
        var amplitudeGroup = paramsGroup.add('group');
        amplitudeGroup.orientation = 'row';
        amplitudeGroup.alignChildren = ['left', 'center'];
        amplitudeGroup.add('statictext', undefined, '振幅 (Amplitude):');
        _controls.amplitudeInput = amplitudeGroup.add('edittext', undefined, '1.0');
        _controls.amplitudeInput.characters = 8;
        _controls.amplitudeInput.helpTip = '范围: 0.1 - 10.0';
        
        // 周期输入
        var periodGroup = paramsGroup.add('group');
        periodGroup.orientation = 'row';
        periodGroup.alignChildren = ['left', 'center'];
        periodGroup.add('statictext', undefined, '周期 (Period):    ');
        _controls.periodInput = periodGroup.add('edittext', undefined, '0.5');
        _controls.periodInput.characters = 8;
        _controls.periodInput.helpTip = '范围: 0.1 - 5.0';
        
        // 缓动类型下拉菜单
        var easingGroup = paramsGroup.add('group');
        easingGroup.orientation = 'row';
        easingGroup.alignChildren = ['left', 'center'];
        easingGroup.add('statictext', undefined, '缓动类型:         ');
        _controls.easingDropdown = easingGroup.add('dropdownlist', undefined, [
            'Ease Out',
            'Ease In',
            'Ease In-Out'
        ]);
        _controls.easingDropdown.selection = 0; // 默认 Ease Out
        _controls.easingDropdown.preferredSize.width = 120;
        
        // 分隔线
        _window.add('panel', undefined, '', {borderStyle: 'black'});
        
        // 按钮区域
        var buttonGroup = _window.add('group');
        buttonGroup.orientation = 'row';
        buttonGroup.alignChildren = ['center', 'center'];
        buttonGroup.spacing = 10;
        
        _controls.applyButton = buttonGroup.add('button', undefined, '应用到选中关键帧');
        _controls.applyButton.preferredSize.width = 150;
        
        _controls.resetButton = buttonGroup.add('button', undefined, '重置');
        _controls.resetButton.preferredSize.width = 80;
        
        // 状态文本
        _controls.statusText = _window.add('statictext', undefined, '就绪', {
            multiline: true
        });
        _controls.statusText.preferredSize.height = 40;
        _controls.statusText.graphics.foregroundColor = _window.graphics.newPen(
            _window.graphics.PenType.SOLID_COLOR,
            [0.5, 0.5, 0.5],
            1
        );
        
        // 绑定事件
        this._bindEvents();
        
        return _window;
    };
    
    /**
     * 绑定事件处理器
     * @private
     */
    this._bindEvents = function() {
        var self = this;
        
        // 振幅输入变化
        _controls.amplitudeInput.onChange = function() {
            var result = _viewModel.updateAmplitude(this.text);
            if (!result.success) {
                self.showError(result.error);
                this.text = _viewModel.getCurrentParams().amplitude.toString();
            }
        };
        
        // 周期输入变化
        _controls.periodInput.onChange = function() {
            var result = _viewModel.updatePeriod(this.text);
            if (!result.success) {
                self.showError(result.error);
                this.text = _viewModel.getCurrentParams().period.toString();
            }
        };
        
        // 缓动类型变化
        _controls.easingDropdown.onChange = function() {
            var easingTypes = ['easeOut', 'easeIn', 'easeInOut'];
            var type = easingTypes[this.selection.index];
            _viewModel.updateEasingType(type);
        };
        
        // 应用按钮
        _controls.applyButton.onClick = function() {
            self.showStatus('正在应用...', 'info');
            
            var result = _viewModel.applyToSelectedProperties();
            
            if (result.success) {
                self.showStatus(result.message, 'success');
            } else {
                self.showError(result.message);
            }
        };
        
        // 重置按钮
        _controls.resetButton.onClick = function() {
            _viewModel.reset();
            self.updateFromModel(_viewModel.getCurrentParams());
            self.showStatus('已重置为默认值', 'info');
        };
    };
    
    /**
     * 显示状态信息
     * @param {string} message
     * @param {string} type - 'info' | 'success' | 'error'
     */
    this.showStatus = function(message, type) {
        _controls.statusText.text = message;
        
        var color;
        switch (type) {
            case 'success':
                color = [0, 0.6, 0]; // 绿色
                break;
            case 'error':
                color = [0.8, 0, 0]; // 红色
                break;
            default:
                color = [0.5, 0.5, 0.5]; // 灰色
        }
        
        _controls.statusText.graphics.foregroundColor = _window.graphics.newPen(
            _window.graphics.PenType.SOLID_COLOR,
            color,
            1
        );
    };
    
    /**
     * 显示错误信息
     * @param {string} message
     */
    this.showError = function(message) {
        this.showStatus(message, 'error');
        alert(message);
    };
    
    /**
     * 从 Model 更新 UI
     * @param {Object} params
     */
    this.updateFromModel = function(params) {
        _controls.amplitudeInput.text = params.amplitude.toString();
        _controls.periodInput.text = params.period.toString();
        
        var easingIndex = {
            'easeOut': 0,
            'easeIn': 1,
            'easeInOut': 2
        }[params.easingType] || 0;
        
        _controls.easingDropdown.selection = easingIndex;
    };
    
    /**
     * 显示窗口
     */
    this.show = function() {
        if (_window) {
            _window.center();
            // 对于 dialog 类型窗口，使用 show() 会阻塞执行直到窗口关闭
            // 这是正确的行为，适合"运行脚本文件"方式
            _window.show();
        }
    };
    
    /**
     * 关闭窗口
     */
    this.close = function() {
        if (_window) {
            _window.close();
        }
    };
}


// ============================================================
// PART 5: Main Initialization - 主初始化代码
// ============================================================

// 调试开关
var DEBUG = true;

/**
 * 调试日志
 * @param {string} message
 */
function log(message) {
    if (DEBUG) {
        $.writeln('[RiveElasticCurve] ' + message);
    }
}

/**
 * 初始化插件
 */
function init() {
    try {
        log('开始初始化插件...');
        
        // 检查 AE 版本
        log('AE 版本: ' + app.version);
        if (parseFloat(app.version) < 23.0) {
            alert('此插件需要 After Effects 2023 或更高版本\n当前版本: ' + app.version);
            return;
        }
        
        // 创建 MVVM 实例
        log('创建 Model 实例...');
        var model = new ElasticCurveModel();
        
        log('创建 ExpressionGenerator 实例...');
        var generator = new ExpressionGenerator();
        
        log('创建 ViewModel 实例...');
        var viewModel = new ElasticCurveViewModel(model, generator);
        
        log('创建 View 实例...');
        var view = new ElasticCurveView(viewModel);
        
        // 绑定 View 到 ViewModel
        viewModel.bindView(view);
        
        log('构建 UI...');
        // 构建并显示 UI
        view.build();
        view.show();
        
        log('插件初始化成功！');
        
    } catch (e) {
        var errorMsg = '插件初始化失败：\n' + e.toString();
        if (e.line) {
            errorMsg += '\n行号: ' + e.line;
        }
        if (e.fileName) {
            errorMsg += '\n文件: ' + e.fileName;
        }
        alert(errorMsg);
        log('错误详情: ' + errorMsg);
    }
}

// 启动插件
init();
