// ExpressionGenerator.jsx
// 表达式生成器：将 Rive 弹性曲线转换为 AE 表达式

/**
 * Rive 弹性曲线表达式生成器
 * @constructor
 */
function ExpressionGenerator() {
    
    /**
     * 生成 AE 表达式代码
     * @param {number} amplitude - 振幅
     * @param {number} period - 周期
     * @param {string} easingType - 缓动类型 ('easeIn' | 'easeOut' | 'easeInOut')
     * @returns {string} AE 表达式代码
     */
    this.generate = function(amplitude, period, easingType) {
        var expression = '';
        
        // 表达式头部：参数定义
        expression += '// Rive Elastic Curve\n';
        expression += '// Generated by Rive Elastic Curve Plugin\n';
        expression += '\n';
        expression += '// 参数\n';
        expression += 'var amplitude = ' + amplitude + ';\n';
        expression += 'var period = ' + period + ';\n';
        expression += 'var PI = Math.PI;\n';
        expression += '\n';
        
        // 计算相位偏移 s
        expression += '// 计算相位偏移\n';
        expression += 'var s = amplitude < 1.0 \n';
        expression += '    ? period / 4.0 \n';
        expression += '    : period / (2.0 * PI) * Math.asin(1.0 / amplitude);\n';
        expression += '\n';
        
        // 实际振幅计算函数
        expression += '// 计算实际振幅\n';
        expression += 'function computeActualAmplitude(time) {\n';
        expression += '    if (amplitude < 1.0) {\n';
        expression += '        var t = Math.abs(s);\n';
        expression += '        var absTime = Math.abs(time);\n';
        expression += '        if (absTime < t) {\n';
        expression += '            var l = absTime / t;\n';
        expression += '            return (amplitude * l) + (1.0 - l);\n';
        expression += '        }\n';
        expression += '    }\n';
        expression += '    return amplitude;\n';
        expression += '}\n';
        expression += '\n';
        
        // 根据缓动类型生成对应的函数
        switch (easingType) {
            case 'easeOut':
                expression += this._generateEaseOut();
                break;
            case 'easeIn':
                expression += this._generateEaseIn();
                break;
            case 'easeInOut':
                expression += this._generateEaseInOut();
                break;
            default:
                expression += this._generateEaseOut(); // 默认 easeOut
        }
        
        expression += '\n';
        
        // 应用到关键帧
        expression += '// 应用到关键帧\n';
        expression += 'if (numKeys > 1) {\n';
        expression += '    var startKey = nearestKey(time);\n';
        expression += '    \n';
        expression += '    if (startKey.time > time) {\n';
        expression += '        if (startKey.index > 1) {\n';
        expression += '            startKey = key(startKey.index - 1);\n';
        expression += '        } else {\n';
        expression += '            startKey = null;\n';
        expression += '        }\n';
        expression += '    }\n';
        expression += '    \n';
        expression += '    if (startKey !== null) {\n';
        expression += '        var endKey = nearestKey(time + thisComp.frameDuration);\n';
        expression += '        \n';
        expression += '        if (endKey.time <= time) {\n';
        expression += '            if (endKey.index < numKeys) {\n';
        expression += '                endKey = key(endKey.index + 1);\n';
        expression += '            } else {\n';
        expression += '                endKey = null;\n';
        expression += '            }\n';
        expression += '        }\n';
        expression += '        \n';
        expression += '        if (endKey !== null && endKey.index > startKey.index) {\n';
        expression += '            var t1 = startKey.time;\n';
        expression += '            var t2 = endKey.time;\n';
        expression += '            var v1 = startKey.value;\n';
        expression += '            var v2 = endKey.value;\n';
        expression += '            var duration = t2 - t1;\n';
        expression += '            var progress = (time - t1) / duration;\n';
        expression += '            var factor = elasticEase(progress);\n';
        expression += '            \n';
        expression += '            value = v1 + (v2 - v1) * factor;\n';
        expression += '        } else {\n';
        expression += '            value;\n';
        expression += '        }\n';
        expression += '    } else {\n';
        expression += '        value;\n';
        expression += '    }\n';
        expression += '} else {\n';
        expression += '    value;\n';
        expression += '}';
        
        return expression;
    };
    
    /**
     * 生成 Ease Out 函数
     * @private
     */
    this._generateEaseOut = function() {
        var code = '';
        code += '// Ease Out 函数\n';
        code += 'function elasticEase(factor) {\n';
        code += '    var time = factor;\n';
        code += '    var actualAmplitude = computeActualAmplitude(time);\n';
        code += '    \n';
        code += '    return actualAmplitude * Math.pow(2.0, -10.0 * time) * \n';
        code += '           Math.sin((time - s) * (2.0 * PI) / period) + 1.0;\n';
        code += '}\n';
        return code;
    };
    
    /**
     * 生成 Ease In 函数
     * @private
     */
    this._generateEaseIn = function() {
        var code = '';
        code += '// Ease In 函数\n';
        code += 'function elasticEase(factor) {\n';
        code += '    var time = factor - 1.0;\n';
        code += '    var actualAmplitude = computeActualAmplitude(time);\n';
        code += '    \n';
        code += '    return -(actualAmplitude * Math.pow(2.0, 10.0 * time) * \n';
        code += '             Math.sin((-time - s) * (2.0 * PI) / period));\n';
        code += '}\n';
        return code;
    };
    
    /**
     * 生成 Ease In-Out 函数
     * @private
     */
    this._generateEaseInOut = function() {
        var code = '';
        code += '// Ease In-Out 函数\n';
        code += 'function elasticEase(factor) {\n';
        code += '    var time = factor * 2.0 - 1.0;\n';
        code += '    var actualAmplitude = computeActualAmplitude(time);\n';
        code += '    \n';
        code += '    if (time < 0.0) {\n';
        code += '        return -0.5 * actualAmplitude * Math.pow(2.0, 10.0 * time) * \n';
        code += '               Math.sin((-time - s) * (2.0 * PI) / period);\n';
        code += '    } else {\n';
        code += '        return 0.5 * (actualAmplitude * Math.pow(2.0, -10.0 * time) * \n';
        code += '               Math.sin((time - s) * (2.0 * PI) / period)) + 1.0;\n';
        code += '    }\n';
        code += '}\n';
        return code;
    };
    
    /**
     * 生成简化版表达式（用于预览）
     * @param {number} amplitude
     * @param {number} period
     * @param {string} easingType
     * @returns {string}
     */
    this.generateSimplified = function(amplitude, period, easingType) {
        return 'Rive Elastic (' + easingType + ')\n' +
               'Amplitude: ' + amplitude + '\n' +
               'Period: ' + period;
    };
}

// 导出
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ExpressionGenerator;
}
